import Navbar from "@/components/Navbar/Navbar";
import AuthProvider from "@/context/auth";
import ChatbotProvider from "@/context/chatbot";
import { Analytics } from "@vercel/analytics/react"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ChatbotProvider>
            <Navbar />
            {children}
          </ChatbotProvider>
        </AuthProvider>
        <Analytics />
      </body>
    </html>
  );
}
